### ISSUE TITLE
[fpp-tools] Revise switches for C++ code gen

### ISSUE THREAD

**Issue by bocchino** [fprime-community/fpp#330]
Changes requested during the F Prime integration:

## fpp-to-cpp

1. When `-u` is enabled, only unit test base class code should be generated, not component autocode.
1. Add a flag `-a` (automatic test setup) to govern the generation of `TesterHelpers.cpp`. When `-a` is present, `TesterHelpers.cpp` is generated when `-u` is present and `-t` is not present. Otherwise `TesterHelpers.cpp` is generated when `-u` and `-t` are both present.

## fpp-filenames

1. Add an `-a` flag and make the behavior match that of `fpp-to-cpp`.

## fpp-depend

1. Eliminate the `-t` option. If necessary in the next round of integration, we can write generated template files to separate files with the suffix `.template`. This may not be necessary, depending on how the integration is done.
1. Have the `-u` flag write the unit test base class files (and only those files) to a separate file, instead of adding the unit test files to the autocoded files reported by `-g`.
1. Add an `-a` flag. When `-a` is present,`TesterHelpers.cpp` is included with the autocode files reported by `-u`. Otherwise it is not so included.

## Tasks

- [x] Update fpp-filenames and unit tests
- [x] Update fpp-to-cpp and unit tests
- [x] Update fpp-depend and unit tests
- [x] Update User's Guide

**Comment by bocchino** [comment]
@LeStarch FYI.
